// settings.yaml 配置项的中文说明。key 为配置路径（点分），如 "risk.gate1.max_positions"。
// 未收录的路径会回退到所在分组（section）的通用说明。

// 顶层分组（section tab）说明，用于 tab 按钮 tooltip
export const SECTION_TITLES: Record<string, string> = {
  app: "应用基础：名称、时区、目录、日志",
  datahub: "数据中枢：数据源优先级、熔断、缓存、行情质量",
  features: "因子打分：各因子权重及按市场状态覆盖",
  regime: "市场状态：大盘状态判定与各状态下的仓位/风险系数",
  selection: "选股初筛：股票池过滤条件、排名截取、LLM 短名单",
  brain: "AI 决策：意图生成门槛、最终精选数量与观察池",
  risk: "风控三道门：事前限额、盘中止盈止损、收盘对账",
  portfolio: "仓位计算：单笔风险预算、权重上限、资金比例",
  execution: "交易执行：滑点控制、下单护栏、成本参数、QMT 连接",
  backtest: "回测设置：初始资金、基准、年化换算、无风险利率",
  evolution: "策略进化：复盘样本要求、滚动训练、因子池升降",
  ops: "运维：通知推送、系统监控、报告输出",
  scheduler: "定时任务：各环节调度时间与开关",
  strategies: "独立策略：尾盘选股法等独立于多因子/Regime 体系的短线策略",
};

// 各配置项说明
export const CONFIG_HINTS: Record<string, string> = {
  // ============ app 应用基础 ============
  "app.name": "应用名称（仅标识用）",
  "app.timezone": "系统时区，默认 Asia/Shanghai",
  "app.data_dir": "本地数据存放目录（SQLite、缓存等）",
  "app.log_dir": "日志文件存放目录",
  "app.log_level": "日志级别：DEBUG / INFO / WARNING / ERROR",

  // ============ datahub 数据中枢 ============
  "datahub.priority.bars": "K 线数据源优先级，前面的失败自动切到后面的",
  "datahub.priority.fundamentals": "财务基本面数据源优先级",
  "datahub.priority.news": "新闻资讯数据源优先级",
  "datahub.circuit_breaker.fail_threshold": "某数据源连续失败达到该次数后熔断，暂停使用",
  "datahub.circuit_breaker.cooldown_seconds": "熔断后冷却多少秒才允许重试",
  "datahub.cache.minute_bar_ttl": "分钟 K 线缓存有效期（秒）",
  "datahub.cache.daily_bar_ttl": "日 K 线缓存有效期（秒），86400=1 天",
  "datahub.cache.fundamental_ttl": "财务数据缓存有效期（秒）",
  "datahub.cache.max_items": "内存缓存最多保留多少条数据",
  "datahub.quality.max_missing_ratio": "K 线缺失比例超过该值时判定数据质量不合格",
  "datahub.quality.max_abs_return": "单根 K 线涨跌幅绝对值超过该值视为异常数据（剔除或告警）",

  // ============ features 因子打分 ============
  "features.weights.mom_20d": "20 日动量因子权重：近一个月涨得多得分高",
  "features.weights.mom_60d": "60 日动量因子权重：近一个季度趋势强度",
  "features.weights.turnover_change": "换手率变化因子权重：量能异动",
  "features.weights.volume_ratio": "量比因子权重：当日成交量相对均量放大程度",
  "features.weights.ma_alignment": "均线多头排列因子权重：短中长期均线向上发散程度",
  "features.weights.atr_pct": "波动率因子权重（负值=波动越大得分越低）",
  "features.weights.money_flow_5d": "5 日资金净流入因子权重",
  "features.weights.money_flow_20d": "20 日资金净流入因子权重",
  "features.weights.roe": "ROE 净资产收益率因子权重（盈利质量）",
  "features.weights.revenue_yoy": "营收同比增速因子权重",
  "features.weights.pe_percentile": "PE 历史分位因子权重（负值=估值越低得分越高）",
  "features.weights.news_sentiment": "新闻情绪因子权重（LLM/舆情打分）",
  "features.regime_weight_overrides": "按市场状态覆盖因子权重。TREND_UP=上升趋势 / RANGE=震荡 / TREND_DOWN=下降趋势，key 为因子名",
  "features.winsorize_quantile": "因子去极值：按该分位数对因子值做缩尾处理，防止极端值干扰排名",

  // ============ regime 市场状态 ============
  "regime.index_symbol": "用于判断大盘状态的基准指数",
  "regime.ma_short": "短期均线周期（日）",
  "regime.ma_long": "长期均线周期（日）",
  "regime.breadth_strong": "市场宽度（上涨家数占比）高于该值判为强势市场",
  "regime.breadth_weak": "市场宽度低于该值判为弱势市场",
  "regime.vol_risk_off": "指数波动率超过该值触发避险模式（RISK_OFF）",
  "regime.drawdown_risk_off": "指数从高点回撤超过该值触发避险模式（RISK_OFF）",
  "regime.position_cap": "各市场状态下的总仓位上限（占总资金比例）",
  "regime.position_cap.TREND_UP": "上升趋势：最高 8 成仓位",
  "regime.position_cap.RANGE": "震荡市：最高 5 成仓位",
  "regime.position_cap.TREND_DOWN": "下降趋势：最高 2 成仓位",
  "regime.position_cap.RISK_OFF": "避险模式：空仓",
  "regime.risk_factor": "各市场状态下的风险系数，用于缩放单笔风险预算",
  "regime.risk_factor.TREND_UP": "上升趋势：按 100% 风险预算开仓",
  "regime.risk_factor.RANGE": "震荡市：按 70% 风险预算开仓",
  "regime.risk_factor.TREND_DOWN": "下降趋势：按 40% 风险预算开仓",
  "regime.risk_factor.RISK_OFF": "避险模式：不开新仓",

  // ============ selection 选股初筛 ============
  "selection.screener.exclude_st": "是否剔除 ST/*ST 股票",
  "selection.screener.min_list_days": "上市天数低于该值的股票剔除（剔除次新股）",
  "selection.screener.exclude_suspended": "是否剔除停牌股票",
  "selection.screener.exclude_limit_locked": "是否剔除一字涨跌停无法交易的股票",
  "selection.screener.min_amount_20d": "20 日平均成交额下限（元），低于该值流动性不足剔除",
  "selection.screener.min_market_cap": "总市值下限（元），低于该值的小盘股剔除",
  "selection.screener.allowed_boards": "允许交易的板块：MAIN=主板 / GEM=创业板 / STAR=科创板",
  "selection.screener.blacklist": "股票代码黑名单，列表内标的永不入选",
  "selection.ranker.top_n": "综合打分排名后最多保留多少只进入下一阶段",
  "selection.ranker.max_per_industry": "同一行业最多入选多少只（行业分散）",
  "selection.llm_shortlist": "送入 LLM 深度研究的短名单数量",

  // ============ brain AI 决策 ============
  "brain.min_intent_score": "买入意图得分低于该值的不进入候选",
  "brain.max_intents": "每轮最多产生多少个买入意图",
  "brain.max_industry_weight": "单一行业持仓权重上限",
  "brain.final_picks_min": "最终精选最少多少只标的",
  "brain.final_picks_max": "最终精选最多多少只标的",
  "brain.rolling.carry_top_n": "观察池中得分前多少名优先保留/直接晋级",
  "brain.rolling.watch_days": "意图在观察池中最多观察多少天",
  "brain.rolling.min_score": "观察池标的晋级为正式意图的最低得分",
  "brain.rolling.max_watch": "观察池最多容纳多少个观察对象",

  // ============ risk.gate1 事前风控 ============
  "risk.gate1.min_list_days": "上市天数低于该值禁止买入",
  "risk.gate1.max_volume_ratio_of_adv": "单笔买入量不得超过该股日均成交量的该比例（避免冲击成本）",
  "risk.gate1.max_single_weight": "单只股票持仓占总资金权重上限",
  "risk.gate1.max_industry_weight": "单一行业持仓占总资金权重上限",
  "risk.gate1.max_positions": "最多同时持有多少只股票",
  "risk.gate1.max_new_positions_per_day": "每天最多新建多少个仓位",
  "risk.gate1.max_correlated_positions": "高相关（走势高度同步）持仓最多多少只",
  "risk.gate1.correlation_threshold": "收益相关系数超过该值视为高相关",
  "risk.gate1.correlation_window": "相关性统计窗口（交易日数）",
  "risk.gate1.cash_buffer": "账户最低保留现金比例",
  "risk.gate1.max_order_value_ratio": "单笔订单金额占总资产比例上限",
  "risk.gate1.max_daily_loss": "当日亏损达到该比例触发停止开新仓",
  "risk.gate1.max_5d_drawdown": "近 5 日回撤达到该比例触发风控收紧",
  "risk.gate1.max_drawdown": "总回撤达到该比例触发熔断（全面停止开仓）",

  // ============ risk.gate2 盘中止盈止损 ============
  "risk.gate2.trailing_activate_profit": "浮盈达到该比例后启用移动止盈",
  "risk.gate2.trailing_drawdown": "移动止盈启用后，从最高浮盈回撤该比例即卖出",
  "risk.gate2.partial_tp": "是否启用分批止盈：按 Intent 确信度档位逐步减仓",
  "risk.gate2.check_interval_seconds": "盘中风控巡检间隔（秒）",

  // ============ risk.gate3 收盘对账 ============
  "risk.gate3.cash_tolerance": "对账时现金差异容差（元），超过则告警",
  "risk.gate3.position_tolerance": "对账时持仓股数差异容差（股），超过则告警",
  "risk.gate3.slippage_alert": "成交滑点超过该比例时告警",

  // ============ portfolio 仓位计算 ============
  "portfolio.base_risk_pct": "单笔交易基础风险预算（占总资金比例）",
  "portfolio.conviction_factor": "按 Intent 确信度缩放仓位的系数：LOW/MEDIUM/HIGH",
  "portfolio.conviction_factor.LOW": "低确信度：按 60% 基础风险开仓",
  "portfolio.conviction_factor.MEDIUM": "中确信度：按 100% 基础风险开仓",
  "portfolio.conviction_factor.HIGH": "高确信度：按 140% 基础风险开仓",
  "portfolio.max_weight_pct": "单票权重上限（与风控 gate1 取更严格者）",
  "portfolio.cash_usage_ratio": "可动用资金比例（保留部分现金不用）",
  "portfolio.total_risk_budget": "全组合总风险预算上限",
  "portfolio.industry_risk_budget": "单行业风险预算上限",
  "portfolio.correlation_penalty": "持仓相关性惩罚系数：与已有持仓越相关，新仓越小",
  "portfolio.min_shares": "最小买入股数（A 股一手=100 股）",

  // ============ execution 交易执行 ============
  "execution.slippage_tolerance": "普通下单可容忍的最大滑点，超过则改限价/放弃",
  "execution.stop_loss_slippage": "止损单可容忍的最大滑点（止损优先保成交）",
  "execution.pending_timeout_seconds": "挂单超过该秒数未成交则撤单/改价",
  "execution.max_chase_times": "未成交时最多追价改单次数",
  "execution.guard.cooldown_seconds": "同一标的两次下单之间的最短间隔（秒）",
  "execution.guard.max_orders_per_symbol_per_day": "同一标的每天最多下单次数",
  "execution.guard.max_orders_per_second": "全局每秒最多下单次数（防刷单）",
  "execution.costs.commission_rate": "佣金费率（双边）",
  "execution.costs.commission_min": "单笔最低佣金（元）",
  "execution.costs.stamp_duty_rate": "印花税率（仅卖出收取）",
  "execution.costs.transfer_fee_rate": "过户费率",
  "execution.costs.base_slippage": "回测/成本测算使用的基准滑点",
  "execution.qmt.path": "QMT 交易端 userdata_mini 目录路径",
  "execution.qmt.account_type": "账户类型（STOCK=股票账户）",
  "execution.qmt.connect_retries": "连接 QMT 失败时最大重试次数",
  "execution.qmt.retry_backoff": "重试间隔基数（秒），按指数退避递增",
  "execution.qmt.max_backoff": "重试间隔上限（秒）",
  "execution.qmt.poll_interval": "轮询 QMT 回报的间隔（秒）",
  "execution.qmt.strategy_name": "QMT 内策略名称标识",

  // ============ backtest 回测 ============
  "backtest.initial_cash": "回测初始资金（元）",
  "backtest.benchmark": "回测基准指数",
  "backtest.trading_days_per_year": "年化换算使用的每年交易日数",
  "backtest.risk_free_rate": "无风险利率（计算夏普比率时扣减）",

  // ============ evolution 策略进化 ============
  "evolution.review_min_samples": "复盘至少需要多少笔交易样本才触发",
  "evolution.cost_drag_warn": "交易成本拖累占收益超过该比例时告警",
  "evolution.stop_hit_warn": "止损触发占比超过该值时告警（策略可能失效）",
  "evolution.train_days": "滚动优化训练窗口长度（天）",
  "evolution.valid_days": "滚动优化验证窗口长度（天）",
  "evolution.step_days": "滚动窗口每次向前滑动步长（天）",
  "evolution.min_windows": "至少需要多少个滚动窗口才认为结果可信",
  "evolution.stability_penalty": "跨窗口表现不稳定的惩罚系数",
  "evolution.min_improve": "新参数相对旧参数至少提升该幅度才采纳",
  "evolution.max_overfit_gap": "训练/验证表现差距超过该值视为过拟合，拒绝采纳",
  "evolution.max_param_step": "参数单次最大调整幅度（防止参数跳变）",
  "evolution.pool.window": "因子池表现评估的统计窗口（天）",
  "evolution.pool.halflife": "因子表现指数加权的半衰期（天），越小越重视近期表现",
  "evolution.pool.min_obs": "最少观测样本数，不足不参与权重调整",
  "evolution.pool.promote_min_obs": "因子晋升（提权）所需的最少观测数",
  "evolution.pool.max_weight": "单因子权重上限",
  "evolution.pool.min_weight": "单因子权重下限",
  "evolution.pool.max_step": "因子权重单次最大调整幅度",
  "evolution.pool.dd_penalty": "回撤惩罚系数：因子导致回撤越大扣分越多",
  "evolution.pool.quarantine_dd": "因子回撤达到该值进入隔离区（暂停使用）",
  "evolution.pool.quarantine_sharpe": "因子夏普低于该值进入隔离区",
  "evolution.pool.recover_sharpe": "隔离区因子夏普恢复到该值以上可解除隔离",
  "evolution.pool.retire_after": "因子被隔离达到该次数后永久退役",

  // ============ ops 运维 ============
  "ops.notify.enabled": "是否启用消息通知",
  "ops.notify.channels": "通知渠道列表（console=控制台输出）",
  "ops.notify.min_level": "最低通知级别：DEBUG / INFO / WARNING / ERROR",
  "ops.notify.throttle_seconds": "同类通知最小发送间隔（秒），防止刷屏",
  "ops.notify.daily_max": "每天最多发送通知条数",
  "ops.notify.timeout_seconds": "单条通知发送超时时间（秒）",
  "ops.monitor.heartbeat_seconds": "心跳上报间隔（秒）",
  "ops.monitor.max_data_lag_days": "行情数据滞后超过该天数告警",
  "ops.monitor.max_llm_cost_ratio": "LLM 调用成本占预算比例超过该值告警",
  "ops.monitor.max_reject_ratio": "风控拒绝率超过该值告警",
  "ops.monitor.min_disk_free_mb": "磁盘剩余空间低于该值（MB）告警",
  "ops.report.output_dir": "日报/周报输出目录",
  "ops.report.top_n": "报告中展示前多少名标的",
  "ops.report.stage_days": "阶段回顾统计窗口（天）",

  // ============ scheduler 定时任务 ============
  "scheduler.timezone": "调度使用的时区",
  "scheduler.enabled": "是否启用定时任务调度器",
  "scheduler.misfire_grace_seconds": "错过计划时间后多少秒内仍补跑（宽限期）",
  "scheduler.jobs.data_sync": "行情数据同步时间",
  "scheduler.jobs.regime": "市场状态判定时间",
  "scheduler.jobs.selection": "选股初筛时间",
  "scheduler.jobs.llm_research": "LLM 深度研究时间",
  "scheduler.jobs.plan": "生成当日交易计划时间",
  "scheduler.jobs.auction_check": "集合竞价检查时间",
  "scheduler.jobs.intraday_start": "盘中监控开始时间",
  "scheduler.jobs.intraday_end": "盘中监控结束时间",
  "scheduler.jobs.intraday_interval_seconds": "盘中巡检间隔（秒）",
  "scheduler.jobs.reconcile": "收盘对账时间",
  "scheduler.jobs.review": "复盘时间",
  "scheduler.jobs.evolve_weekday": "策略进化执行星期（0=周一 … 6=周日）",
  "scheduler.jobs.evolve": "策略进化执行时间",
  "scheduler.jobs.tail_pick_select": "尾盘选股法：T 日选股/买入时刻",
  "scheduler.jobs.tail_pick_exit": "尾盘选股法：T+1 隔夜离场时刻",

  // ============ strategies 独立策略 ============
  "strategies.tail_pick.enabled": "是否启用尾盘选股法（独立短线策略）。默认关闭；启用后调度器在尾盘选股、次日开盘离场",
  "strategies.tail_pick.select_time": "T 日选股/买入时刻（尾盘，如 14:30）",
  "strategies.tail_pick.exit_window_start": "T+1 离场窗口起点（开盘后，如 09:30）",
  "strategies.tail_pick.exit_window_end": "T+1 离场窗口终点（一夜持股：开盘 30min 内离场）",
  "strategies.tail_pick.min_pct_change": "① 涨幅下界（如 0.03=3%）",
  "strategies.tail_pick.max_pct_change": "① 涨幅上界（如 0.05=5%）",
  "strategies.tail_pick.weak_min_pct_change": "V4.0 弱市买跌带下界：指数<MA20 时当日涨幅 ≥ 此值（-0.01=-1%）",
  "strategies.tail_pick.weak_max_pct_change": "V4.0 弱市买跌带上界：弱市当日涨幅 ≤ 此值（0.015=+1.5%，微红微绿=主力护盘/抛压枯竭）",
  "strategies.tail_pick.min_volume_ratio": "② 量比下界（当日量/近5日均量，默认 1.0；V4.0 弱市停用）",
  "strategies.tail_pick.min_turnover_rate": "④ 换手率下界",
  "strategies.tail_pick.max_turnover_rate": "④ 换手率上界",
  "strategies.tail_pick.min_float_market_cap": "⑤ 流通市值下界（元），如 50 亿",
  "strategies.tail_pick.max_float_market_cap": "⑤ 流通市值上界（元），如 500 亿",
  "strategies.tail_pick.volume_ladder_ratio": "⑥ 阶梯放量（日线层）：今日量 ≥ 昨日量 × 该倍数",
  "strategies.tail_pick.volume_ladder_segments": "⑥ 阶梯放量（分时层）：午后连续竞价时段（13:00 起）等分的段数（各段量逐段递增）",
  "strategies.tail_pick.volume_ladder_seg_tolerance": "⑥ 阶梯放量（分时层）：后段量 ≥ 前段量 × 该倍数（0.9=允许微降 10%）",
  "strategies.tail_pick.shrink_vol_max_ratio": "V4.0 缩量过滤：弱市量比 < 该值才入选（1.2=温和放量以内），停用③量比下限/⑥阶梯放量",
  "strategies.tail_pick.vol_spike_exclude_ratio": "V4.0 异常放量剔除：量比 ≥ 该倍数（2.0）强弱市一律剔除（疑似拉高出货）",
  "strategies.tail_pick.min_intraday_outperf_vs_index": "⑦ 跑赢大盘最小幅度（个股当日涨幅 − 沪深300 当日涨幅）",
  "strategies.tail_pick.chip_vwap_tolerance_pct": "⑧ 筹码结构 VWAP 容差：尾盘收 < VWAP×(1+容差) 即通过（默认 0.01=+1%，避免边界误杀）",
  "strategies.tail_pick.overnight_stop_pct": "隔夜硬止损：T+1 开盘较成本跌超该比例立即砍",
  "strategies.tail_pick.max_positions": "同时持有上限（只）",
  "strategies.tail_pick.position_fraction": "每只占用可用现金比例上限",
  "strategies.tail_pick.cash_usage_ratio": "现金使用上限（留部分缓冲）",
  "strategies.tail_pick.universe_top_n": "选股候选池粗筛规模",
  "strategies.tail_pick.require_minute_bars": "真实/paper 回测需分钟线；无分钟线时自动降级（标记非真实业绩）",
  "strategies.tail_pick.gap_protect_enabled": "缺口保护：T+1 平开/低开（开盘≤昨收）时触发；深低开开盘价即卖锁住跳空缺口",
  "strategies.tail_pick.gap_buffer_enabled": "缺口保护·5分钟缓冲：平开/微低开不立即卖，等 9:30-9:35 触及成本保本即走，未触及则 9:35 离场（防洗盘割肉）",
  "strategies.tail_pick.gap_buffer_pct": "缺口缓冲幅度：开盘在成本 ±该幅度内进入 5 分钟缓冲（默认 0.5%）",
  "strategies.tail_pick.breakeven_trigger_pct": "保本触发：开盘 5min 内触及 成本×(1+该值) 后，止损线上移至成本（保本单）",
  "strategies.tail_pick.take_profit_pct": "止盈：触及 成本×(1+该值) 立即落袋，不等窗口结束（V4.0：1.8%→2.8%）",
  "strategies.tail_pick.hard_stop_pct": "V4.0 硬止损：触及 成本×(1−该值)（默认 -1.2%）立即市价离场，动量分支亦保底",
  "strategies.tail_pick.vwap_exit_enabled": "VWAP 止损：V4.0 起默认关闭（让位硬止损）；开启后 bar 收盘跌破当日分时均价即离场",
  "strategies.tail_pick.market_filter_enabled": "大市温度计双模式仓位：强市满仓追涨 / 强市广度闸门空仓 / 弱市侦察兵仓位买跌 / 绝对空仓",
  "strategies.tail_pick.market_ma_days": "条件A：沪深300 收盘须站上的均线天数，站上且广度达标满仓运行（默认 MA20）",
  "strategies.tail_pick.weak_market_adv_min": "强市广度闸门：指数站上均线时上涨家数 > 该值才满仓，否则空仓（默认 2500）",
  "strategies.tail_pick.weak_market_position_ratio": "V4.0 弱市仓位：指数跌破均线但广度≥绝对空仓线时的侦察兵仓位比例（0.2=2成）",
  "strategies.tail_pick.breadth_block_below": "绝对空仓线：上涨家数 < 该值绝对空仓（默认 1000）；介于该值与 2500 之间为震荡市/弱市侦察兵仓位试错",
  "strategies.tail_pick.market_breadth_required": "启用广度分档：关闭后弱市不做半仓分档，直接空仓",
  "strategies.tail_pick.gapup_threshold_pct": "高开阈值：T+1 开盘较昨收高开 > 该比例（0.005=0.5%）→ 开盘市价卖半仓，剩余走保本/止盈/VWAP 链",
  "strategies.tail_pick.gapdown_threshold_pct": "低开阈值：T+1 开盘较昨收低开 < -该比例 → 开盘不卖，等 low_open_check_time 判定翻红",
  "strategies.tail_pick.low_open_check_time": "低开判定时点：该 bar 收盘前最高价曾回到昨收之上（翻红）转正常离场链，否则市价砍仓（默认 09:45）",
  "strategies.tail_pick.open_momentum_enabled": "隔夜动量：高开卖半仓后开盘价>昨收且首根 bar 放量 → 剩余半仓取消 1.8% 止盈，持有至 hold_until 市价离场",
  "strategies.tail_pick.open_momentum_vol_mult": "动量放量倍数：首根 bar 量 ≥ T 日平均每 bar 量 × 该倍数才认定放量（默认 2.0）",
  "strategies.tail_pick.open_momentum_hold_until": "动量分支市价离场时刻（默认 10:30）",
  "strategies.tail_pick.sector_enabled": "板块效应：按东财行业当日涨幅排名筛选/加权（映射为当前快照，回测有幸存者偏差）",
  "strategies.tail_pick.sector_top_n": "热门行业前 N：当日行业涨幅排名前 N 的候选买入名义额 ×sector_boost_mult",
  "strategies.tail_pick.sector_bottom_n": "弱势行业后 N：当日行业涨幅排名后 N 的候选直接剔除",
  "strategies.tail_pick.sector_boost_mult": "热门仓位倍数：命中前 N 行业的标的买入名义额倍数（默认 2.0）",
  "strategies.tail_pick.exclude_st": "排除 ST/*ST",
  "strategies.tail_pick.min_list_days": "上市天数下限（交易日）",
  "strategies.tail_pick.exclude_suspended": "排除停牌",
  "strategies.tail_pick.exclude_limit_locked": "排除一字涨跌停封死",
  "strategies.tail_pick.allowed_boards": "允许板块：MAIN=主板 / GEM=创业板",
};

// 按路径取说明；未收录时逐级向上找父级说明，再回退到分组通用说明
export function hintOf(path: string): string {
  const hit = CONFIG_HINTS[path];
  if (hit) return hit;
  const parts = path.split(".");
  for (let i = parts.length - 1; i > 0; i--) {
    const parent = CONFIG_HINTS[parts.slice(0, i).join(".")];
    if (parent) return parent;
  }
  const sec = parts[0];
  return SECTION_TITLES[sec] ? `【${sec}】${SECTION_TITLES[sec]}` : "";
}
